### PR TITLE
Add GitBook config

### PR DESCRIPTION
**Pull request by yourtion**
Online reading http://spark-internals.books.yourtion.com/ 

 Downloads

- PDF https://www.gitbook.com/download/pdf/book/yourtion/sparkinternals
- EPUB https://www.gitbook.com/download/epub/book/yourtion/sparkinternals
- MOBI https://www.gitbook.com/download/mobi/book/yourtion/sparkinternals

### CODE REVIEW

**Comment by zzl0** [comment]
:beers:

**Comment by JerryLead** [comment]
Awesome, thank you yourtion!
I can download the EPUP and MOBI, but cannot download the PDF version? It the link correct?

**Comment by yourtion** [comment]
@JerryLead I have no idea why cannot download PDF, maybe is gitbook's bug.

https://www.gitbook.com/book/yourtion/sparkinternals/details

**Comment by JerryLead** [comment]
This link is correct, I will merge this pull request, thanks!

**Comment by yourtion** [comment]
@JerryLead I update gitbook just now. I can download PDF this time, you can try to download PDF again.

screen shot 2015-07-19 at 1 12 58 pm

**Pull request merged**
